In [17]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten, Dropout
from keras.layers import Conv2D,MaxPooling2D

model=Sequential()

model.add(Conv2D(256,(3,3),input_shape=[50,50,1]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
#The first CNN layer followed by Relu and MaxPooling layers

model.add(Conv2D(128,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
#The second convolution layer followed by Relu and MaxPooling layers

model.add(Flatten())
#Flatten layer to stack the output convolutions from second convolution layer
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(32,activation='relu'))
model.add(Dropout(0.5))
#Dense layer of 64 neurons
model.add(Dense(2,activation='softmax'))
#The Final layer with two outputs for two categories

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [20]:
model.load_weights('catsvsdogs.h5')

In [31]:
import os
import cv2
import numpy as np

test_path='test1'

img_names=os.listdir(test_path)
category_dict={0:'Cat',1:'Dog'}

for img_name in img_names:
    img=cv2.imread(os.path.join(test_path,img_name))
    h,w=img.shape[0:2] #height and width eka

    #preprocessing (As done for the training images)
    test_img=cv2.resize(img,(50,50))
    test_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    test_img=test_img/255
    test_img=test_img.reshape(1,50,50,1) #neural netowrk eka 4d input ekak illna nisa 4d krgnnwa image eka. 
    #mul tyna 1 thmi 1 image ekak nisa. multiple image tbba nam aulk na 1k image ekk nisa manually denwa.
    
    results=model.predict(test_img)
    label=np.argmax(results,axis=1)[0] #probability 2d array eken wedi eka gnnwa.
    acc=int(np.max(results,axis=1)[0]*100)
    
    print(results,label,category_dict[label],acc) 
    
    img[0:50,0:w]=[0,255,0]
    cv2.putText(img,category_dict[label],(20,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    cv2.putText(img,str(acc)+'%',(120,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    
    cv2.imshow('LIVE',img)
    k=cv2.waitKey(1000)
    if(k==27):
        break
cv2.destroyAllWindows()

[[0.60146487 0.39853504]] 0 Cat 60
[[0.6408268 0.3591732]] 0 Cat 64
[[0.09983511 0.9001649 ]] 1 Dog 90
[[0.05003335 0.9499666 ]] 1 Dog 94
[[0.19162592 0.8083741 ]] 1 Dog 80
[[0.89868826 0.10131173]] 0 Cat 89
[[0.69221294 0.30778706]] 0 Cat 69
[[0.00546221 0.9945378 ]] 1 Dog 99
[[0.7641496 0.2358504]] 0 Cat 76
[[0.89742744 0.10257255]] 0 Cat 89
[[0.7537745  0.24622548]] 0 Cat 75
[[0.9915554  0.00844466]] 0 Cat 99
[[0.6195277 0.3804723]] 0 Cat 61
[[0.629595   0.37040496]] 0 Cat 62
[[0.526004   0.47399598]] 0 Cat 52
[[0.21118057 0.78881943]] 1 Dog 78
[[0.06567486 0.9343251 ]] 1 Dog 93
[[0.8173553  0.18264468]] 0 Cat 81
[[0.65769064 0.34230936]] 0 Cat 65


In [2]:
video=cv2.VideoCapture('Funny Cat and Dog Videos Compilation   15 Minutes.mp4')

category_dict={0:'Cat',1:'Dog'}

while(True):
    
    ret,img=video.read()
    
    h,w=img.shape[0:2]

    #preprocessing (As done for the training images)
    test_img=cv2.resize(img,(50,50))
    test_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    test_img=test_img/255
    test_img=test_img.reshape(1,50,50,1)
    
    results=model.predict(test_img)
    label=np.argmax(results,axis=1)[0]
    acc=int(np.max(results,axis=1)[0]*100)
    
    category=category_dict[label]
    
    print(results,label,category,acc)
    
    if(acc<60):
        
        category='NONE'
        
    img[0:50,0:w]=[0,255,0]
    cv2.putText(img,category,(20,40),cv|2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    cv2.putText(img,str(acc)+'%',(120,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    
    cv2.imshow('LIVE',img)
    k=cv2.waitKey(100)
    if(k==27):
        break
cv2.destroyAllWindows()

SyntaxError: invalid syntax (<ipython-input-2-24ea70bb1241>, line 30)